name: Issue Digest
description: |
  Create a discussion post with a digest of issues
author: sethrylan
branding:
  icon: book
  color: blue

inputs:
  repo:
    description: |
      repository to digest; defaults to the current repo
    required: false
  since:
    description: |
      optional: datetime to lookback to, defaults to 24hr ago
    required: false
  query:
    description: |
      optional: issue query string, defaults to the repo where the workflow is
      hosted for the owner/repo, as "repo:<repo> updated:>=<24hr-ago>"
    required: false
  title:
    description: |
      optional: title of discussion post to create (or add a comment to);
      defaults to Issue Digest <current date UTC>
    required: false
  comment:
    description: |
      optional: Text/Markdown for the comment intro
    required: false
  intro:
    description: |
      optional: Text/Markdown for the discussion intro
    required: false
  discussionCategory:
    description: |
      optional: Discussion category to use; defaults to General
    required: false
  models:
    description: |
      optional: whether to use GitHub Models to summarize the issues
    required: false
  lookback:
    description: |
      optional: time duration (e.g., 2hr, 1w) for event timeline lookback, used for model summary; defaults to 1 day (1d)
    required: false

outputs:
  discussionUrl:
    description: |
      The URL of the discussion post created or updated

runs:
  using: node20
  main: dist/index.js
